import type {
  AtlasPart,
  AtlasSystem,
  GeometryKind,
  SystemId,
  Vec3,
} from './types';
import { applyComponentDimensions } from './component-dimensions';
import { applyReferenceHardware } from './reference-hardware';
import { robotSystem } from './robot';

function part(
  id: string,
  name: string,
  fullName: string,
  geometry: GeometryKind,
  position: Vec3,
  size: Vec3,
  color: string,
  description: string,
  specifications: Record<string, string>,
  relatedComponents: string[],
  lesson: string,
  explodedPosition?: Vec3,
): AtlasPart {
  return {
    id,
    name,
    fullName,
    geometry,
    position,
    size,
    color,
    description,
    specifications,
    relatedComponents,
    lesson,
    category: 'Computer hardware',
    relatedTopics: Object.values(specifications).slice(0, 2),
    modelObjectName: id,
    cameraTarget: position,
    explodedPosition: explodedPosition ?? [
      position[0] * 1.65,
      position[1] * 1.5,
      position[2] + 1.1,
    ],
  };
}
const desktop: AtlasPart[] = [
  part(
    'case',
    'PC Case',
    'Computer chassis',
    'case',
    [0, 0, 0],
    [2.65, 4.5, 3.65],
    '#687482',
    'The structural enclosure protects the hardware, supports mounting, and guides airflow through the computer.',
    {
      Role: 'Protection & airflow',
      'Form factor': 'Mid-tower concept',
      Material: 'Steel / aluminum',
    },
    ['motherboard', 'fans', 'psu'],
    'A chassis must match the motherboard form factor and provide enough clearance for the graphics card and CPU cooler. Intake and exhaust fans work together to remove heat.',
    [-1.9, 0, -0.5],
  ),
  part(
    'motherboard',
    'Motherboard',
    'Main printed circuit board',
    'board',
    [-0.5, 0.35, -1.35],
    [2.05, 2.8, 0.09],
    '#244f49',
    'The main circuit board connects the processor, memory, storage, and expansion devices through electrical pathways.',
    {
      'Form factor': 'ATX-inspired',
      Connections: 'PCIe, DIMM, SATA',
      Role: 'System interconnect',
    },
    ['cpu', 'ram', 'gpu', 'psu'],
    'The motherboard carries power and signals. Its chipset and processor determine which interfaces, memory generations, and expansion features are supported.',
    [-2.6, 0.4, -0.6],
  ),
  part(
    'cpu',
    'CPU',
    'Central Processing Unit',
    'cpu',
    [-0.6, 0.9, -1.14],
    [0.65, 0.65, 0.13],
    '#b7bec7',
    'The processor fetches, decodes, and executes instructions, coordinating the work performed by the computer.',
    {
      Interface: 'CPU socket',
      Workload: 'General-purpose computing',
      Cooling: 'Heatsink required',
    },
    ['motherboard', 'ram', 'cooler'],
    'The CPU repeatedly fetches an instruction, decodes its operation, and executes it. Caches keep frequently used data close; system memory holds the larger working set.',
    [-1.6, 2, 0.65],
  ),
  part(
    'cooler',
    'CPU Cooler',
    'Processor cooling assembly',
    'cooler',
    [-0.6, 0.95, -0.48],
    [1.02, 1.12, 1.04],
    '#a3adb9',
    'A heatsink and fan transfer thermal energy away from the processor to maintain a safe operating temperature.',
    {
      Method: 'Forced-air cooling',
      Parts: 'Heatsink + fan',
      Mount: 'CPU cooler bracket',
    },
    ['cpu', 'fans', 'case'],
    'Heat moves from the CPU through thermal interface material into the heatsink. Its fins increase surface area, while the fan carries heated air into the chassis airflow.',
    [-1.25, 2.3, 2.15],
  ),
  part(
    'gpu',
    'GPU',
    'Graphics Processing Unit',
    'gpu',
    [-0.13, -0.35, 0.02],
    [2.28, 0.52, 1.22],
    '#424a56',
    'A specialized processor designed for graphics rendering and highly parallel computational workloads.',
    {
      Interface: 'PCI Express',
      Memory: 'Dedicated VRAM',
      Power: 'Slot + auxiliary supply',
    },
    ['cpu', 'motherboard', 'psu'],
    'The CPU submits work to the GPU through PCI Express. Many GPU execution units process workloads in parallel, with dedicated VRAM holding textures, framebuffers, and computation data.',
    [2.35, -0.3, 1.7],
  ),
  part(
    'ram',
    'RAM',
    'Random Access Memory',
    'ram',
    [0.65, 0.98, -1.02],
    [0.42, 1.7, 0.18],
    '#466c59',
    'Fast, volatile memory holds programs and data that the processor is actively using.',
    {
      Interface: 'DIMM slots',
      Retention: 'Volatile',
      Role: 'Active working memory',
    },
    ['cpu', 'motherboard'],
    'RAM loses its contents when power is removed. Memory capacity controls how much active data can be held, while bandwidth and latency influence how efficiently the processor can access it.',
    [1.65, 2, -0.35],
  ),
  part(
    'psu',
    'Power Supply',
    'Power Supply Unit',
    'psu',
    [-0.2, -1.62, -0.5],
    [2.1, 0.83, 2.15],
    '#343c48',
    'The power supply converts mains AC into regulated low-voltage DC rails used by the computer.',
    {
      Conversion: 'AC to regulated DC',
      Outputs: '12 V, 5 V, 3.3 V',
      Connectors: 'ATX, CPU, PCIe',
    },
    ['motherboard', 'gpu', 'ssd'],
    'The PSU provides several regulated voltage rails. The motherboard and graphics card perform further voltage conversion near sensitive chips. This model illustrates connections, not safe repair procedures.',
    [-0.3, -2.6, 0.55],
  ),
  part(
    'ssd',
    'SSD / Storage',
    'Solid-State Drive',
    'ssd',
    [1, -0.8, -0.68],
    [0.16, 1.05, 0.85],
    '#8094a7',
    'Nonvolatile flash storage retains the operating system, applications, and files when the system is powered off.',
    {
      Type: '2.5-inch SATA concept',
      Storage: 'NAND flash',
      Retention: 'Nonvolatile',
    },
    ['motherboard', 'psu'],
    'An SSD controller manages flash memory and presents a block-storage interface to the operating system. This conceptual drive uses SATA; M.2 drives may use SATA or PCIe/NVMe.',
    [2.75, -1.45, -0.1],
  ),
  part(
    'fans',
    'Case Fans',
    'Chassis airflow fans',
    'fans',
    [0, 0.6, 1.47],
    [2.08, 3.1, 0.16],
    '#576271',
    'Chassis fans move cooler air into the enclosure and exhaust heated air from internal components.',
    {
      Arrangement: 'Front intake concept',
      Control: 'DC or PWM',
      Purpose: 'System airflow',
    },
    ['case', 'cooler', 'gpu'],
    'Airflow depends on fan direction, vent restriction, and placement. A useful path delivers outside air to heat-producing hardware and gives the warmed air an exit.',
    [0.65, 0.4, 3.35],
  ),
  part(
    'rear-fan',
    'Exhaust Fan',
    'Rear chassis exhaust fan',
    'fans',
    [0.4, 1.42, -1.56],
    [1.15, 1.15, 0.16],
    '#586577',
    'An exhaust fan helps remove warm air from the rear of the chassis.',
    {
      Direction: 'Exhaust',
      Connection: 'Fan header',
      Control: 'Speed control',
    },
    ['fans', 'case', 'cooler'],
    'Intake and exhaust should form a coherent airflow path. An exhaust fan near the CPU helps carry warmed air out of the enclosure.',
    [1.3, 2.25, -2.35],
  ),
];
// One scene unit = 100 mm. X runs rear-to-front, Y up, Z out from the tray.
const desktopDimensions: Record<
  string,
  {
    position: Vec3;
    size: Vec3;
    rotation?: Vec3;
    displayRotation: Vec3;
    clearancePosition: Vec3;
    dimensionsMm: string;
  }
> = {
  case: {
    position: [0, 0, 0],
    size: [4.5, 4.6, 2.2],
    displayRotation: [0.06, -0.28, 0],
    clearancePosition: [-3.3, 0, -0.8],
    dimensionsMm: '450 × 460 × 220 mm chassis',
  },
  motherboard: {
    position: [-0.65, 0.45, -0.88],
    size: [2.44, 3.05, 0.12],
    displayRotation: [0, 0, 0],
    clearancePosition: [-0.65, 0.45, 0.9],
    dimensionsMm: '305 × 244 mm ATX board',
  },
  cpu: {
    position: [-0.9, 1.05, -0.76],
    size: [0.4, 0.4, 0.045],
    displayRotation: [0, 0, 0],
    clearancePosition: [-0.9, 1.05, 1.8],
    dimensionsMm: '40 × 40 mm example package',
  },
  cooler: {
    position: [-0.9, 1.05, 0.045],
    size: [1.25, 1.25, 1.55],
    displayRotation: [-0.16, -0.65, 0],
    clearancePosition: [-0.9, 1.05, 3.1],
    dimensionsMm: '125 × 125 × 155 mm cooler',
  },
  gpu: {
    position: [-0.55, -0.63, -0.245],
    size: [2.8, 0.45, 1.2],
    displayRotation: [-Math.PI / 2, 0, 0],
    clearancePosition: [-0.55, -0.63, 2.3],
    dimensionsMm: '280 × 120 × 45 mm graphics card',
  },
  ram: {
    position: [0.19, 1.03, -0.62],
    size: [0.2, 1.3335, 0.34],
    displayRotation: [0, -Math.PI / 2, 0],
    clearancePosition: [0.8, 1.03, 1.5],
    dimensionsMm: '2 × 133.35 mm DIMMs',
  },
  psu: {
    position: [-1.42, -1.75, -0.05],
    size: [1.4, 0.86, 1.5],
    displayRotation: [0.42, -0.35, 0],
    clearancePosition: [-3.3, -1.75, 0.2],
    dimensionsMm: '150 × 86 × 140 mm PSU',
  },
  ssd: {
    position: [0.91, -0.75, -0.99],
    size: [0.6985, 1.0, 0.07],
    displayRotation: [0, 0, 0],
    clearancePosition: [1.35, -0.75, -1.6],
    dimensionsMm: '100 × 69.85 × 7 mm SATA SSD',
  },
  fans: {
    position: [2.02, 0.25, 0],
    size: [1.2, 3.7, 0.25],
    rotation: [0, Math.PI / 2, 0],
    displayRotation: [0, 0, 0],
    clearancePosition: [3.15, 0.25, 0],
    dimensionsMm: '3 × 120 × 120 × 25 mm fans',
  },
  'rear-fan': {
    position: [-2.04, 1.27, 0.12],
    size: [1.2, 1.2, 0.25],
    rotation: [0, -Math.PI / 2, 0],
    displayRotation: [0, 0, 0],
    clearancePosition: [-3.1, 1.27, 0],
    dimensionsMm: '120 × 120 × 25 mm exhaust',
  },
};
const desktopVisualSizes: Record<string, Vec3> = {
  case: [4.5, 4.9, 2.25],
  motherboard: [2.44, 3.05, 0.35],
  cpu: [0.4, 0.4, 0.065],
  cooler: [1.3, 1.25, 1.55],
  gpu: [2.88, 0.5, 1.31],
  psu: [1.46, 1.01, 1.53],
  ssd: [0.6985, 1, 0.105],
  fans: [1.225, 3.725, 0.3],
  'rear-fan': [1.225, 1.225, 0.3],
};
for (const p of desktop) {
  Object.assign(p, desktopDimensions[p.id], { detail: 'desktop' });
  p.visualSize = desktopVisualSizes[p.id] ?? p.size;
  p.cameraTarget = p.position;
  p.specifications['Model dimensions'] = p.dimensionsMm!;
}

const mb = (
  id: string,
  name: string,
  kind: GeometryKind,
  pos: Vec3,
  size: Vec3,
  desc: string,
  spec: Record<string, string>,
  related: string[],
  lesson: string,
  color = '#586775',
) => part(id, name, name, kind, pos, size, color, desc, spec, related, lesson);
const motherboard: AtlasPart[] = [
  mb(
    'pcb',
    'Circuit Board',
    'board',
    [0, 0, -0.2],
    [3.4, 4, 0.09],
    'A multilayer board routes electrical power and signals between hardware components.',
    { Structure: 'Multilayer PCB' },
    ['socket', 'dimm', 'pcie'],
    'Copper traces on different layers connect devices, while power and ground planes provide reference and supply paths.',
    '#25584f',
  ),
  mb(
    'socket',
    'CPU Socket',
    'socket',
    [-0.25, 0.85, 0],
    [1, 1, 0.2],
    'The socket mechanically secures the processor and connects it electrically to the board.',
    { Compatibility: 'CPU-specific' },
    ['vrm', 'dimm'],
    'Socket shape alone does not guarantee CPU compatibility; firmware and chipset support also matter.',
  ),
  mb(
    'dimm',
    'DIMM Slots',
    'ram',
    [1, 0.7, 0],
    [0.5, 2.05, 0.18],
    'Memory sockets connect system RAM to the processor memory controller.',
    { Purpose: 'System memory' },
    ['socket'],
    'Memory generations have different electrical and mechanical requirements.',
  ),
  mb(
    'pcie',
    'PCIe Slots',
    'slot',
    [-0.35, -0.85, 0],
    [1.9, 0.16, 0.2],
    'Expansion slots connect graphics cards and other high-speed peripherals.',
    { Interface: 'PCI Express' },
    ['socket', 'chipset'],
    'PCIe connections use lanes. A physically long slot may have fewer electrically connected lanes.',
  ),
  mb(
    'vrm',
    'VRM',
    'chip',
    [-1.05, 1.23, 0],
    [0.38, 1.12, 0.22],
    'Voltage regulator modules step the supply down to voltages required by the CPU.',
    { Role: 'Voltage conversion' },
    ['socket', 'cpu-power'],
    'VRMs use switching stages, inductors, and capacitors to provide stable high-current power.',
  ),
  mb(
    'chipset',
    'Chipset',
    'chip',
    [0.65, -0.9, 0],
    [0.65, 0.65, 0.2],
    'The chipset provides additional I/O connectivity and communicates with the processor.',
    { Role: 'Peripheral I/O' },
    ['sata', 'usb', 'pcie'],
    'The division of connections between CPU and chipset varies by platform. Chipset devices share an upstream link.',
  ),
  mb(
    'battery',
    'CMOS Battery',
    'battery',
    [-0.75, -1.5, 0],
    [0.46, 0.46, 0.13],
    'A coin cell powers the real-time clock and supports retained settings on many systems.',
    { 'Typical cell': 'CR2032' },
    ['bios'],
    'Firmware itself is stored in nonvolatile flash. The coin cell primarily keeps the real-time clock running when other power is absent.',
    '#bbc3c9',
  ),
  mb(
    'bios',
    'BIOS Chip',
    'chip',
    [0.2, -1.65, 0],
    [0.28, 0.32, 0.1],
    'Nonvolatile flash stores the firmware used to initialize the system.',
    { Firmware: 'UEFI / BIOS' },
    ['socket', 'battery'],
    'Firmware initializes hardware and locates a bootloader, which then starts the operating system.',
  ),
  mb(
    'sata',
    'SATA Ports',
    'port',
    [1.42, -1.22, 0],
    [0.3, 0.62, 0.28],
    'SATA ports attach compatible storage drives through data cables.',
    { Interface: 'SATA' },
    ['chipset'],
    'A SATA drive generally needs both a data connection and a separate power connection.',
  ),
  mb(
    'm2',
    'M.2 Slot',
    'slot',
    [0.15, -0.35, 0],
    [1.35, 0.24, 0.12],
    'A compact connector supports compatible expansion modules such as SSDs.',
    { Keying: 'Module-dependent' },
    ['socket', 'chipset'],
    'M.2 is a form factor. Depending on the slot, a storage module may communicate over PCIe/NVMe or SATA.',
  ),
  mb(
    'atx-power',
    '24-pin Power',
    'port',
    [1.45, 0.75, 0],
    [0.25, 0.95, 0.25],
    'The main ATX connector supplies motherboard power.',
    { Connector: '24-pin ATX' },
    ['vrm', 'cpu-power'],
    'The connector carries multiple power rails and control signals between the supply and motherboard.',
  ),
  mb(
    'cpu-power',
    'CPU Power',
    'port',
    [-1.25, 1.8, 0],
    [0.5, 0.22, 0.25],
    'A dedicated connector supplies 12 V to the CPU voltage regulators.',
    { Connector: 'EPS-style' },
    ['vrm', 'atx-power'],
    'CPU power and graphics power connectors are not interchangeable even when they look similar.',
  ),
  mb(
    'usb',
    'USB Headers',
    'pins',
    [0.8, -1.8, 0],
    [0.5, 0.15, 0.2],
    'Internal headers connect case USB ports to the motherboard.',
    { Role: 'Front-panel USB' },
    ['chipset'],
    'Internal USB headers vary by generation and connector. Check orientation and the board documentation.',
  ),
  mb(
    'fan-header',
    'Fan Headers',
    'pins',
    [-0.45, 1.8, 0],
    [0.3, 0.13, 0.16],
    'Headers provide fan power and speed sensing or control.',
    { Control: 'DC / PWM' },
    ['vrm'],
    'A four-pin fan header can supply a PWM control signal while reading a tachometer signal from the fan.',
  ),
  mb(
    'audio',
    'Audio Controller',
    'chip',
    [-1.25, -1.17, 0],
    [0.28, 0.3, 0.1],
    'An audio codec converts between digital audio and analog signals.',
    { Conversion: 'DAC / ADC' },
    ['chipset'],
    'Output uses digital-to-analog conversion; microphone input uses analog-to-digital conversion.',
  ),
  mb(
    'ethernet',
    'Ethernet Controller',
    'chip',
    [-1.25, 0.15, 0],
    [0.3, 0.32, 0.1],
    'Network hardware handles the wired Ethernet connection.',
    { Network: 'Ethernet' },
    ['chipset'],
    'Ethernet hardware implements link functions and exchanges frames with the host system.',
  ),
];
const arduino: AtlasPart[] = [
  mb(
    'pcb',
    'Uno Board',
    'board',
    [0, 0, -0.18],
    [3.4, 2.5, 0.1],
    'An Arduino Uno-inspired board connects a microcontroller to power, programming, and I/O headers.',
    { Reference: 'Uno R3 concept' },
    ['atmega', 'digital', 'analog'],
    'This is a simplified educational model. Consult the exact board pinout before connecting real hardware.',
    '#146d80',
  ),
  mb(
    'atmega',
    'ATmega328P',
    'chip',
    [0.4, -0.35, 0],
    [1.35, 0.4, 0.2],
    'The main microcontroller runs the uploaded program and controls I/O.',
    { Architecture: '8-bit AVR', Clock: '16 MHz' },
    ['crystal', 'digital', 'analog'],
    'A microcontroller combines a processor, memory, and peripherals. Your setup function runs once, followed by repeated calls to loop.',
  ),
  mb(
    'usb',
    'USB Connector',
    'port',
    [-1.55, 0.65, 0],
    [0.7, 0.6, 0.5],
    'The USB Type-B connection provides programming communication and can supply power.',
    { Connector: 'USB Type-B' },
    ['usb-controller'],
    'On the Uno R3 design, USB communication passes through a separate USB-to-serial microcontroller.',
    '#b3bac5',
  ),
  mb(
    'usb-controller',
    'USB Controller',
    'chip',
    [-0.9, 0.6, 0],
    [0.35, 0.35, 0.1],
    'The ATmega16U2 on the Uno R3 bridges USB and serial communication.',
    { Reference: 'ATmega16U2' },
    ['usb', 'atmega'],
    'This device translates USB communication for the main microcontroller serial interface.',
  ),
  mb(
    'regulator',
    'Voltage Regulator',
    'chip',
    [-1.1, -0.75, 0],
    [0.35, 0.45, 0.15],
    'The regulator provides the board supply from an appropriate external input.',
    { 'Board logic': '5 V' },
    ['power'],
    'External input limits and heat dissipation matter. Use the official board specifications for a physical circuit.',
  ),
  mb(
    'crystal',
    'Clock Resonator',
    'crystal',
    [-0.2, 0.2, 0],
    [0.4, 0.18, 0.12],
    'The main controller uses a 16 MHz ceramic resonator on the Uno R3 reference design.',
    { Frequency: '16 MHz' },
    ['atmega'],
    'Clock edges synchronize processor operations. The USB controller has its own clock circuitry.',
    '#b8b3a2',
  ),
  mb(
    'reset',
    'Reset Button',
    'button',
    [-1.2, 1, 0],
    [0.23, 0.23, 0.17],
    'The reset button restarts execution on the main microcontroller.',
    { Signal: 'Active-low reset' },
    ['atmega'],
    'Reset initializes the controller again. It does not erase the uploaded program.',
  ),
  mb(
    'digital',
    'Digital Pins',
    'pins',
    [0.35, 1.08, 0],
    [2.4, 0.18, 0.3],
    'Digital pins D0–D13 provide digital I/O; selected pins support alternate peripheral functions.',
    { PWM: 'D3, D5, D6, D9, D10, D11', UART: 'D0 / D1' },
    ['atmega'],
    'PWM rapidly switches a digital output. It changes the duty cycle and is not a true analog voltage output. Individual pin inspection is planned.',
    '#477799',
  ),
  mb(
    'analog',
    'Analog Pins',
    'pins',
    [0.95, -1.05, 0],
    [1.1, 0.18, 0.3],
    'A0–A5 feed the analog-to-digital converter and may also serve as digital I/O.',
    { ADC: '10-bit', 'I²C': 'A4 / A5' },
    ['atmega'],
    'The ADC compares the input with a reference voltage and produces a numerical reading. Use the board specifications to determine safe input limits.',
    '#669281',
  ),
  mb(
    'power',
    'Power Pins',
    'pins',
    [-0.55, -1.05, 0],
    [1.2, 0.18, 0.3],
    'Power headers expose supply, ground, reset, and reference-related connections.',
    { Labels: '5 V, 3.3 V, GND, Vin' },
    ['regulator'],
    'Supply pins have different purposes and current limits. Never assume every labeled voltage is an unrestricted power source.',
    '#b59a61',
  ),
  mb(
    'icsp',
    'ICSP Header',
    'pins',
    [1.35, 0.15, 0],
    [0.3, 0.45, 0.28],
    'The programming header exposes SPI and reset for in-circuit programming.',
    { Signals: 'MISO, MOSI, SCK' },
    ['atmega'],
    'An external programmer can program the controller through this header.',
  ),
  mb(
    'leds',
    'Onboard LEDs',
    'led',
    [0.1, 0.62, 0],
    [0.38, 0.16, 0.1],
    'Status LEDs indicate power and communication; the built-in L LED is associated with D13.',
    { Indicators: 'ON, RX, TX, L' },
    ['digital'],
    'The Blink example toggles the built-in LED, making it a useful first test of the programming workflow.',
    '#d8aa5e',
  ),
];
const rectifier: AtlasPart[] = [
  mb(
    'ac',
    'AC Source',
    'source',
    [-2.75, 0, 0],
    [0.8, 0.8, 0.3],
    'The source alternates polarity across the bridge input terminals.',
    { Input: 'Alternating current' },
    ['d1', 'd3'],
    'This conceptual low-voltage circuit demonstrates rectification. No mains-powered construction is implied.',
    '#718ba9',
  ),
  ...(['d1', 'd2', 'd3', 'd4'] as const).map((id, i) => ({
    ...mb(
      id,
      `Diode D${i + 1}`,
      'diode',
      [
        [-0.6, 0.6, 0],
        [0.6, 0.6, 0],
        [-0.6, -0.6, 0],
        [0.6, -0.6, 0],
      ][i] as Vec3,
      [0.22, 0.55, 0.22],
      'A diode conducts primarily in one direction. Two bridge diodes conduct during each AC half-cycle.',
      { Role: 'Rectification', Stripe: 'Cathode marker' },
      ['ac', 'capacitor'],
      'D1 and D4 conduct when the left AC terminal is positive relative to the right. D2 and D3 conduct during the opposite half-cycle. The load polarity stays the same; the two conducting diode drops reduce the available voltage.',
      '#505761',
    ),
    rotation: [0, 0, ([-1, 1, 1, -1][i] * Math.PI) / 4] as Vec3,
  })),
  mb(
    'capacitor',
    'Filter Capacitor',
    'capacitor',
    [2.25, 0, 0],
    [0.55, 0.85, 0.55],
    'The capacitor stores charge near voltage peaks and supplies the load between peaks.',
    { Role: 'Ripple reduction' },
    ['load', 'd1', 'd2'],
    'Larger capacitance generally reduces ripple for a given load and frequency. Approximate ripple is load current divided by ripple frequency times capacitance. This model is illustrative, not a simulation.',
    '#557eab',
  ),
  mb(
    'load',
    'Load Resistor',
    'resistor',
    [3.35, 0, 0],
    [0.3, 0.85, 0.3],
    'The load consumes energy from the rectified output.',
    { Output: 'Unidirectional, with ripple' },
    ['capacitor'],
    'Full-wave rectification produces ripple at twice the AC source frequency. A filter smooths it, but does not by itself regulate the output voltage.',
    '#b3986d',
  ),
];

motherboard.push(
  mb(
    'rear-io',
    'Rear I/O',
    'port',
    [0, 0, 0],
    [1, 1, 1],
    'Shielded connectors expose USB, networking, video and audio interfaces at the back of the computer.',
    { Interfaces: 'USB, Ethernet, video, audio' },
    ['ethernet', 'audio', 'chipset'],
    'Connector shields help with grounding and interference. Available ports depend on the board and processor.',
  ),
);
arduino.push(
  mb(
    'dc-jack',
    'DC Power Jack',
    'port',
    [0, 0, 0],
    [1, 1, 1],
    'The barrel jack accepts an external DC supply for the onboard regulator.',
    { Connector: 'Center-positive barrel jack' },
    ['regulator', 'power-caps'],
    'The input passes through the board power circuitry before supplying the regulated logic rail.',
  ),
  mb(
    'power-caps',
    'Power Capacitors',
    'capacitor',
    [0, 0, 0],
    [1, 1, 1],
    'Electrolytic capacitors smooth the input and regulated power rails.',
    { Type: 'Polarized electrolytic' },
    ['dc-jack', 'regulator'],
    'Bulk capacitors store charge to reduce supply changes. Smaller nearby capacitors handle faster transients.',
  ),
);
rectifier.unshift(
  mb(
    'pcb',
    'Circuit Board',
    'board',
    [0, 0, 0],
    [1, 1, 1],
    'An example printed circuit board supports the components and connects the bridge and output network.',
    { Layout: 'Full-wave bridge with parallel filter and load' },
    ['d1', 'd2', 'd3', 'd4', 'capacitor', 'load'],
    'AC enters the two side nodes of the bridge. The top and bottom nodes supply positive and negative DC to the capacitor and load.',
    '#315d4d',
  ),
);
const acTerminal = rectifier.find((p) => p.id === 'ac')!;
acTerminal.name = 'AC Input';
acTerminal.fullName = 'Low-voltage AC input terminal';
acTerminal.description =
  'A two-pole screw terminal connects an external low-voltage AC source to the bridge.';
for (const [id, parts] of [
  ['motherboard', motherboard],
  ['arduino', arduino],
  ['rectifier', rectifier],
] as const)
  applyComponentDimensions(parts, id);
applyReferenceHardware(desktop, motherboard, arduino);

export const systems: Record<SystemId, AtlasSystem> = {
  robot: robotSystem,
  desktop: {
    id: 'desktop',
    name: 'Desktop Computer',
    category: 'Computer Systems',
    number: '01',
    description: 'A flagship desktop, component by component.',
    parts: desktop,
    camera: [7, 4.2, 9],
    overview:
      'Explore the MSI Maestro build with an RTX 5090 Founders Edition, Maximus Z890 Extreme, and Intel Core Ultra 9 285K. Select a part to inspect its model and specifications.',
    features: { xray: true, signal: false, pins: false },
    connections: [
      { from: 'cpu', to: 'ram', kind: 'data' },
      { from: 'motherboard', to: 'gpu', kind: 'data' },
      { from: 'psu', to: 'gpu', kind: 'power' },
    ],
  },
  motherboard: {
    id: 'motherboard',
    name: 'Motherboard',
    category: 'Electronics',
    number: '02',
    description: 'The architecture of connection.',
    parts: motherboard,
    camera: [-2.5, 1.8, 6.5],
    overview:
      'Explore the ASUS ROG Crosshair X870E Edition 20, following the supplied black-and-gold reference. Separate the copper heatsink and thermal covers to reveal the AM5 board beneath.',
    features: { xray: false, signal: false, pins: false },
    connections: [
      { from: 'socket', to: 'dimm', kind: 'data' },
      { from: 'atx-power', to: 'vrm', kind: 'power' },
    ],
  },
  arduino: {
    id: 'arduino',
    name: 'Arduino Uno',
    category: 'Microcontrollers',
    number: '03',
    description: 'An introduction to physical computing.',
    parts: arduino,
    camera: [-2.3, 2.6, 7],
    overview:
      'Inspect an Uno R3-inspired board and learn how its controller, programming interface, power, and I/O work together. Pin groups are selectable; individual pin mode is coming later.',
    features: { xray: false, signal: false, pins: false },
    connections: [
      { from: 'atmega', to: 'digital', kind: 'signal' },
      { from: 'atmega', to: 'analog', kind: 'signal' },
    ],
  },
  rectifier: {
    id: 'rectifier',
    name: 'Bridge Rectifier',
    category: 'Circuits',
    number: '04',
    description: 'From alternating to direct current.',
    parts: rectifier,
    camera: [2, 2, 9],
    overview:
      'Explore a physical bridge circuit with four axial diodes, an AC input, a filter capacitor, and a load. Explode to inspect each part. Waveforms and animated half-cycle paths are planned.',
    features: { xray: false, signal: false, pins: false },
    connections: [
      { from: 'ac', to: 'd1', kind: 'signal' },
      { from: 'ac', to: 'd3', kind: 'signal' },
      { from: 'd1', to: 'capacitor', kind: 'power' },
      { from: 'capacitor', to: 'load', kind: 'power' },
    ],
  },
};
for (const system of Object.values(systems))
  for (const p of system.parts) if (!p.subsystem) p.category = system.category;
export const systemList = Object.values(systems).sort((a, b) =>
  a.number.localeCompare(b.number),
);
export function isSystemId(value: string | null): value is SystemId {
  return !!value && Object.hasOwn(systems, value);
}
